name: bioenv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - numpy
  - pandas=3.0.0
  - scipy
  - matplotlib
  - seaborn
  - dask

  - biopython=1.86
  - pysam=0.23.3
  - samtools=1.22
  - bwa=0.7.19
  - macs3=3.0.3
  - fastp=1.0.1